### ISSUE TITLE
更新后报401错误

### ISSUE THREAD

**Issue by Payne-Wang** [Jiabinone/notdiamond2api#16]
大佬，之前旧的镜像可以使用，但是更新最新版后，会报鉴权错误：
![image](https://github.com/user-attachments/assets/cefa1eeb-88c5-46e3-bee5-3a640f6874b1)

去官网上登录是没有问题的，说明账号没有问题

docker-compose.yml
```
services:
  flask-app:
    image: fjiabinc/notdiamond2api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AUTH_EMAIL=aaaaa@aaaa.com
      - AUTH_PASSWORD=aaaaa
      - AUTH_ENABLED=true
      - AUTH_TOKEN=aaaa
    networks:
      - oneapi-all
networks:
  oneapi-all:
    external: true
    name: oneapi-all
```
